version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - python babel_runner.py compile source/_extensions/acacia_ext acacia_ext

python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: source/conf.py
